acme_accueil:
    resource: "@AcmeAccueilBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"

accueil:
    path: /
    defaults: { _controller: AcmeAccueilBundle:Default:index }
