acme_accueil:
    resource: "@AcmeAccueilBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"

# La route site.com/ dirige le traitement vers le controleur du bundle Accueil : Default, vers la fonction indexAction
accueil:
    path: /
    defaults: { _controller: AcmeAccueilBundle:Default:index }
